model_params:
  name: "VAE"
  in_channels: 30
  latent_dim: 5

data_params:
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 4
  nan_rate: 0.7

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VAE"
