model_params:
  name: "MLP"
  in_channels: 8 # latent 5 + meta 3 (x, y, z)
  out_channels: 5 # latent 5
  neighbors: 5
  meta_dims:
    - "x"
    - "y"
    - "z"

data_params:
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 4
  neighbor_size: 5

train_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: "gpu"
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "MLP"
